name = "kkmail"
main = "src/index.js"
compatibility_date = "2024-10-22"
workers_dev = true

# Custom domain for email service
[env.production]
routes = [
  { pattern = "mail.yourdomain.com/*", zone_name = "yourdomain.com" }
]

# Secrets are set via: wrangler secret put SECRET_NAME --env production
# Required secrets:
# - RESEND_API_KEY: Your Resend API key
# - JWT_SECRET: A strong random string for JWT signing
# - ADMIN_EMAIL: Admin email address for initial setup

# D1 Database binding
[[env.production.d1_databases]]
binding = "DB"
database_name = "kkmail-db"
database_id = "your_database_id_here"

# KV binding for caching
[[env.production.kv_namespaces]]
binding = "KV"
id = "your_kv_namespace_id_here"

# R2 bucket for email storage (optional)
# [[env.production.r2_buckets]]
# binding = "EMAIL_STORAGE"
# bucket_name = "kkmail-storage"